unbind C-b
set-option -g prefix Q
bind-key Q send-prefix

unbind v
unbind h 
unbind w
unbind x

bind-key v split-window -v
bind-key b split-window -h
bind-key x kill-pane
bind-key w kill-window
bind-key          , command-prompt "rename-window '%%'"

bind-key r source-file ~/.tmux.conf

# changing design
set -g status-style fg=white 
set -g status-style bold 
set -g status-left ""
set -g status-right ""
set -g window-status-current-format ' [#I:#W] '
set -g window-status-format '#I:#W'
set -g base-index 1
set -g renumber-windows on

# vim keybindings for panel hopping
bind-key -T prefix h select-pane -L
bind-key -T prefix j select-pane -D
bind-key -T prefix k select-pane -U
bind-key -T prefix l select-pane -R
